//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaculdadeSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avaliacao()
        {
            this.AvaliacaoPerguntas = new HashSet<AvaliacaoPergunta>();
            this.AvaliacaoRespostas = new HashSet<AvaliacaoResposta>();
        }
    
        public int IdAvaliacao { get; set; }
        public string DescricaoAvaliacao { get; set; }
        public Nullable<DateTime> Expiracao { get; set; }
        public string Titulo { get; set; }
        public int IdUsuario { get; set; }
        public int IdPerfil { get; set; }
        public Nullable<bool> AvaliacaoStatus { get; set; }
        public List<Pergunta> Perguntas { get; set; }
    
        public virtual Perfil Perfil { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoPergunta> AvaliacaoPerguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoResposta> AvaliacaoRespostas { get; set; }
    }
}
