//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaculdadeSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerguntaTipoResposta
    {
        public int IdPerguntaTipoResposta { get; set; }
        public int IdPergunta { get; set; }
        public int IdtipoResposta { get; set; }
    
        public virtual Pergunta Pergunta { get; set; }
        public virtual TipoResposta TipoResposta { get; set; }
    }
}
