//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaculdadeSI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pergunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pergunta()
        {
            this.AvaliacaoPerguntas = new HashSet<AvaliacaoPergunta>();
            this.AvaliacaoRespostas = new HashSet<AvaliacaoResposta>();
            this.PerguntaTipoRespostas = new HashSet<PerguntaTipoResposta>();
           
        }
    
        public int IdPergunta { get; set; }
        public string DescricaoPergunta { get; set; }
        public Nullable<bool> PerguntaStatus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoPergunta> AvaliacaoPerguntas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvaliacaoResposta> AvaliacaoRespostas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerguntaTipoResposta> PerguntaTipoRespostas { get; set; }

        //public List<int> IdTipoResposta { get; set; }

        public String TipoResposta { get; set; }


    }
}
